Extension { #name : #WAHtmlCanvas }

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qApp [

	^ self brush: QuasarApp new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qAvatar [

	^ self brush: QuasarAvatar new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qBtn [

	^ self brush: QuasarBtn new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qBtnGroup [

	^ self brush: QuasarBtnGroup new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qCard [

	^ self brush: QuasarCard new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qCardActions [

	^ self brush: QuasarCardActions new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qCardSection [

	^ self brush: QuasarCardSection new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qCheckbox [

	^ self brush: QuasarCheckbox new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qChip [

	^ self brush: QuasarChip new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qColor [

	^ self brush: QuasarColor new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qDate [

	^ self brush: QuasarDate new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qDialog [

	^ self brush: QuasarDialog new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qDrawer [

	^ self brush: QuasarDrawer new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qExpansionItem [

	^ self brush: QuasarExpansionItem new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qFab [

	^ self brush: QuasarFab new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qFabAction [

	^ self brush: QuasarFabAction new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qField [

	^ self brush: QuasarField new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qFile [

	^ self brush: QuasarFile new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qFooter [

	^ self brush: QuasarFooter new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qForm [

	^ self brush: QuasarForm new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qHeader [

	^ self brush: QuasarHeader new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qIcon [

	^ self brush: QuasarIcon new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qImg [

	^ self brush: QuasarImg new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qInput [

	^ self brush: QuasarInput new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qItem [

	^ self brush: QuasarItem new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qItemLabel [

	^ self brush: QuasarItemLabel new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qItemSection [

	^ self brush: QuasarItemSection new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qLayout [

	^ self brush: QuasarLayout new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qList [

	^ self brush: QuasarList new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qMarkupTable [

	^ self brush: QuasarMarkupTable new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qMenu [

	^ self brush: QuasarMenu new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qPage [

	^ self brush: QuasarPage new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qPageContainer [

	^ self brush: QuasarPageContainer new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qPageSticky [

	^ self brush: QuasarPageSticky new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qPopupProxy [

	^ self brush: QuasarPopupProxy new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qQuasarBreadcrumbs [

	^ self brush: QuasarBreadcrumbs new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qQuasarBreadcrumbsEl [

	^ self brush: QuasarBreadcrumbsEl new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qRadio [

	^ self brush: QuasarRadio new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qRouteTab [

	^ self brush: QuasarRouteTab new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qRouterTemplate [

	^ self brush: QuasarRouterTemplate new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qRouterView [

	^ self brush: QuasarRouterView new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qScrollArea [

	^ self brush: QuasarScrollArea new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qSelect [

	^ self brush: QuasarSelect new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qSeparator [

	^ self brush: QuasarSeparator new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qSpace [

	^ self brush: QuasarSpace new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTab [

	^ self brush: QuasarTab new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTabPanel [

	^ self brush: QuasarTabPanel new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTabPanels [

	^ self brush: QuasarTabPanels new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTable [

	^ self brush: QuasarTable new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTabs [

	^ self brush: QuasarTabs new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTd [

	^ self brush: QuasarTd new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTemplate [

	^ self brush: QuasarTemplate new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTh [

	^ self brush: QuasarTh new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTime [

	^ self brush: QuasarTime new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qToggle [

	^ self brush: QuasarToggle new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qToolbar [

	^ self brush: QuasarToolbar new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qToolbarTitle [

	^ self brush: QuasarToolbarTitle new
]

{ #category : #'*Quasar-Components' }
WAHtmlCanvas >> qTr [

	^ self brush: QuasarTr new
]
