Class {
	#name : #QuasarDemoObjectA,
	#superclass : #Object,
	#instVars : [
		'string1',
		'integer1',
		'boolean1'
	],
	#category : #'Quasar-Demo-Basic'
}

{ #category : #accessing }
QuasarDemoObjectA >> boolean1 [

	^ boolean1
]

{ #category : #accessing }
QuasarDemoObjectA >> boolean1: anObject [

	boolean1 := anObject
]

{ #category : #accessing }
QuasarDemoObjectA >> integer1 [

	^ integer1
]

{ #category : #accessing }
QuasarDemoObjectA >> integer1: anObject [

	integer1 := anObject
]

{ #category : #accessing }
QuasarDemoObjectA >> string1 [

	^ string1
]

{ #category : #accessing }
QuasarDemoObjectA >> string1: anObject [

	string1 := anObject
]
